repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    # -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=3500']


-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.2
    hooks:
      - id: clang-format
        args: [--verbose]
        types_or: [c, c++]
        # include: '\.(cpp|hpp|h|c|cc|cxx)$'